// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbRo9dYcyhkWTQSE14QglvLIsyAOCG_s',
    appId: '1:791953660680:web:b1bcac0ca2cd82358baabd',
    messagingSenderId: '791953660680',
    projectId: 'scholar-chat-app-c85bc',
    authDomain: 'scholar-chat-app-c85bc.firebaseapp.com',
    storageBucket: 'scholar-chat-app-c85bc.firebasestorage.app',
    measurementId: 'G-N8EVKJL2SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwPUlqZ9GrKGfw03M14QCXfrFEriZ42o',
    appId: '1:791953660680:android:9f80c7e4109a43d98baabd',
    messagingSenderId: '791953660680',
    projectId: 'scholar-chat-app-c85bc',
    storageBucket: 'scholar-chat-app-c85bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZD0etugWWehci7-_jcUPEmNr9UJZV0IY',
    appId: '1:791953660680:ios:5171a7a962c48e448baabd',
    messagingSenderId: '791953660680',
    projectId: 'scholar-chat-app-c85bc',
    storageBucket: 'scholar-chat-app-c85bc.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZD0etugWWehci7-_jcUPEmNr9UJZV0IY',
    appId: '1:791953660680:ios:5171a7a962c48e448baabd',
    messagingSenderId: '791953660680',
    projectId: 'scholar-chat-app-c85bc',
    storageBucket: 'scholar-chat-app-c85bc.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgbRo9dYcyhkWTQSE14QglvLIsyAOCG_s',
    appId: '1:791953660680:web:fef23ef45947a94b8baabd',
    messagingSenderId: '791953660680',
    projectId: 'scholar-chat-app-c85bc',
    authDomain: 'scholar-chat-app-c85bc.firebaseapp.com',
    storageBucket: 'scholar-chat-app-c85bc.firebasestorage.app',
    measurementId: 'G-WE6BFYD3EK',
  );
}
